# edge_yaw_viewer에서 's' 키로 저장하면 이 파일이 덮어써짐
edge_detector:
  ros__parameters:
    img_topic: "/camera/camera_head/color/image_raw/compressed"

    canny_low:    50
    canny_high:   150
    hough_thresh: 40
    min_length:   60
    max_gap:      15

    ## 이미지 비율
    roi_top_pct:   50
    roi_bot_pct:   100
    roi_left_pct:  20
    roi_right_pct: 80

    max_abs_yaw_deg: 30.0
    enable_service_name: /approach/edge_detector/set_enable

    debug_log: true
    debug_image: true
